### ISSUE TITLE
Range errors continuous when using plugin offset start

### ISSUE THREAD

**Issue by narration-sd** [videojs/videojs-youtube#371]
This happens if trying the old 4.x offset plugin, which is pretty simple, and also with the new nice and more modern one, videojs-time-offset from https://github.com/dogusdigital/videojs-time-offset.  

The video plays, but there are a mass of faults collecting in the console, and if the video is too long, the player hangs.  This doesn't happen with non-Youtube videos (mp4, etc) which are not using the youtube tech - no errors there.,

```

VIDEOJS: RangeError: Maximum call stack size exceeded
    at InjectedScript.RemoteObject (<anonymous>:1208:29)
    at Object.InjectedScript._wrapObject (<anonymous>:370:20)
    at Object.InjectedScript.wrapObject (<anonymous>:298:25)
    at _logType (http://dev.dev/resources/lib/js/video.js:19257:19)
    at Object.log [as default] (http://dev.dev/resources/lib/js/video.js:19195:3)
    at Player.techCall_ (http://dev.dev/resources/lib/js/video.js:10609:34)
    at Player.currentTime (http://dev.dev/resources/lib/js/video.js:10742:12)
    at Player.player.currentTime (http://dev.dev/resources/lib/js/videojs-time-offset.js:141:37)
    at Player.player.currentTime (http://dev.dev/resources/lib/js/videojs-time-offset.js:149:14)
    at CurrentTimeDisplay.updateContent (http://dev.dev/resources/lib/js/video.js:7058:94)
```

**Comment by Yi-Zhou** [comment]
Hi, @narration-sd, 

I am not using videojs-time-offset but I had a similar issue with another plugin https://github.com/cladera/videojs-offset/

The error occured for me was because videojs-offset tries to call `Player.__super__.currentTime` to update the `currentTime` of its "parent" on the event "timeupdate", while in YouTube.js, that will cause "timeupdate" to be recursively triggered and thus the function is recursively called without an end.

I solved this by commenting out `this.trigger('timeupdate');` in the function `setCurrentTime` in YouTube.js. **I know it is a dirty solution and it is dangerous**, but anyway, it worked for me so far. You may also have to make a dive into the source code and make some other modifications to meet your needs. 

Hope my comment may help you if you still have this problem. And please let me know if anyone else has a better solution.

**Comment by narration-sd** [comment]
Thanks for your thoughts, Yi-Zhou.

The truth is that I had gotten much more into this, and made some more complicated code changes that actually worked. But I found the state of videojs and particularly the youtube tech  at the time was very unproductive for such things, so left the project behind after laying the best hints I could given available time.

There's been a lot of work recently, particularly I think to make some of the necessary calls  actually function again in the youtube tech. Once this settles down, I think plugins like this will become  much easier to write correct code for. 

Then I will look again -- maybe  you also...

Kind regards,
Clive.

**Comment by gkatsev** [comment]
I think a lot has changed with videojs 5 and the youtube tech as well. I'm going to close this issue but please open a new issue if you try out the latest versions and are still seeing issues. Thanks.
