### ISSUE TITLE
Load videojs with requirejs

### ISSUE THREAD

**Issue by marvhock** [videojs/videojs-youtube#373]
Hi,
there is an issue when trying to use videojs-youtube together with requireJS.

Youtube.js is trying to define "video.js" for amd/requirejs. But that makes it impossible to use a path pointing to the directory where videojs is. So, as videojs would mostly be installed in another directory, it would make sense to use the path to "video.js" which is defined in requirejs config.

To make that possible, "video.js" should just be changed to "videojs" inside Youtube.js on the part where it is defined for amd.

Ill just create an PR according to this issue. But I'am just wondering if there was some other reason it was written "video.js" maybe.

**Comment by dbettini** [comment]
I'm using it and it works with webpack + Babel (ES6->ES5). Since the module is called 'video.js', I don't understand why it should be changed. I tried changing it to what you proposed and it breaks my build, while with 'video.js' it works fine.

**Comment by marvhock** [comment]
Well if you just changed that one line of my PR you have to have a path "videojs" defined too in RequireJS. Similair had to be done with webpack I guess. 

See this issue here https://github.com/twitter/typeahead.js/issues/1211
Also see https://github.com/twitter/typeahead.js/issues/1211

Using Requirejs you must not use file extension for define.

**Comment by dbettini** [comment]
Yes, you are right. I'm not using RequireJS, but Typescript import/require syntax (which is ES6 style). In other words, it should never even affect my build, but it does because of another bug, which is wrong detection of module resolution. I'll submit the issue and PR tomorrow (it should be merged in the same release as your PR, so it doesn't break other webpack builds).

**Comment by Joeao** [comment]
This should be closed now, right? I loaded it up with RequireJS successfully.

**Comment by marvhock** [comment]
PR was accepted. Sadly I cant get last changes on NPM. I really wonder how my Commit is listed on release 2.0.8 where 2.0.8 was already there before. So I guess there should be another release to make changes take affect?

**Comment by Joeao** [comment]
I believe so. I'm using source from the master branch rather than 2.0.8.

**Comment by gkatsev** [comment]
If it's been merged and the commit was made before the 2.0.8 release, in the history it'll look like it was made before 2.0.8 but won't actually be available in 2.0.8. If you look at your commit directly, you can see what tags that commit is included in.

Also, I feel like we probably shouldn't be relying on our own UMD implementation but modifying this project to use browserify and have it output a UMD build that works with both requirejs and globals but also let browserify and webpack users just require the project directly. Like how videojs and new versions of contrib-hls work now.

**Comment by dutscher** [comment]
hi there, i run into the same as marvhock. my build with r.js fails now because "video.js" isnt found.
if we change the line 25 in Youtube.js  to this "define(['videojs'], function(videojs){" than everything works fine!

in 2.0.7 it called "videojs".

what is the state? because some other errors are fixxed in 2.0.8

cheers

**Comment by gkatsev** [comment]
Should definitely be available now in 2.1.0.
