### ISSUE TITLE
Play fullscreen but the resolution not full

### ISSUE THREAD

**Issue by luutruong** [videojs/videojs-youtube#375]
As the title. When I try to play video at mode full screen and the video not full as it must.

**Comment by gkatsev** [comment]
This is probably completely up to youtube and there's nothing we can do.
We should probably provide the resolution selector, though.

**Comment by AlexJF** [comment]
In my case, the issue was that when going fullscreen, the video size would remain the same and be centered in a fullscreen black panel. This happened with IE11 and Chrome but not with Firefox.

Stumbled across this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=256247

So if you suffer from similar symptoms make sure to remove max-width and max-height from ancestors and the video should now occupy full-screen.

**Comment by gkatsev** [comment]
Interesting, we could probably add removing max-width and max-height in fullscreen to the plugin.

**Comment by gkatsev** [comment]
Ah, I see. This isn't an issue with videojs-youtube itself (I can't find any reference to `max-height`. But it's good to know for users that stumble on this. Ancestors of the player potentially can't have those properties in fullscreen.
