### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by techyguy16** [videojs/videojs-youtube#393]
Hi,

I'm trying to play youtube video in VideoJS player by using videojs-youtube plug in. 
But it's showing 'No compatible source was found for this media'. error. 
Can anyone one correct the code please ?

--------------------------------------------------------------------------
Code  
https://664bad0acc92f006a71c08155e690287e75daf01.googledrive.com/host/0B9AYxEDEuckcSUJiS2RZSnIycTQ/test%20player.html

Thank you :)

**Comment by gkatsev** [comment]
Your example is broken, the youtube.js it's trying to load ends up being an html page and that's why it's failing since videojs it loading fine but then it doesn't know what to do with the youtube video.
Hope that helps. 
Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.
