### ISSUE TITLE
Ignored "autoplay: false" parameter

### ISSUE THREAD

**Issue by musashinm** [videojs/videojs-youtube#406]
Hi,

I'm using this plugin with VideoJS 5.11.6 and I don't figured out how to disable autoplay. Here's the video tag:

```
<video class='video-js vjs-nzn-skin vjs-big-play-centered' data-setup='{ "sources": [ { "type": "video/youtube", "src": "https://www.youtube.com/watch?v=ixxQZuQcKi4"} ], "techOrder": [ "youtube" ], "youtube": { "ytControls": 2 } }' id='nzn_mediacenter_video'></video>
```

I already try to pass `"autoplay": false` in `data-setup` JSON.

**Comment by gkatsev** [comment]
This is probably because youtube handles [autoplay itself](https://developers.google.com/youtube/player_parameters#autoplay). We should probably translate the player-level autoplay parameter to a youtube level option.
As a workaround, you should be able to do something like `youtube: { "ytControls": 2, "autoplay": 0 }`

**Comment by gkatsev** [comment]
`autoplay: false` in options or removing the autoplay attribute from the video element works for me for disabling autoplay. With `autoplay: true` option or `autoplay` attribute enabling autoplay.

**Comment by danvucore** [comment]
Hi gkatsev,
I think option autoplay not work. I use version videojs-youtube:2.5 and videojs:7.0.5. 
When set options autoplay to false, It still runs with the browser on PC. with mobile is still show progress and not play video.

Hope you look at it.
Thank
Dan
