### ISSUE TITLE
Streaming Video from S3 Bucket and Cloudfront

### ISSUE THREAD

**Issue by Neuroforge** [videojs/videojs-youtube#504]
Hello,

I hope you are well.

I have an avi and mp3 video stored in an AWS S3 Bucket, then i have a Cloud Front distribution linked to this S3 bucket.

I can download both of these files from either the S3 or CloudFront endpoints in a browser.

**S3 Bucket Link Example**
https://s3-us-west-1.amazonaws.com/xxxxxxxxxx/jellyfish-25-mbps-hd-hevc.mp4
https://s3-us-west-1.amazonaws.com/xxxxxxxxxx/jellyfish-25-mbps-hd-hevc.avi

**Cloud Front Link Example**
https://xxxxxxx.cloudfront.net/jellyfish-25-mbps-hd-hevc.mp4
https://xxxxxxx.cloudfront.net/jellyfish-25-mbps-hd-hevc.avi

When i create a VideoJs instance using the mp4 link with type="video/mp4" i get the following error.

> video.min.js:23 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
> i {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
> code
> :
> 4
> message
> :
> "The media could not be loaded, either because the server or network failed or because the format is not supported."
> __proto__
> :
> Object

When i create a VideoJs instance using the avi link with type="video/avi" i get the following error.

NOTE: The mp4 was transcoded with the following parameters....

**The video was transcoded using AWS Elastic Transcoder.
HLS v3 (Apple HTTP Live Streaming), 400 kilobits/second | 1351620000001-200050

**1351620000001-200050**
(https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/system-presets.html)**

What type of transcoding should be used when preparing videos for VideoJs?

**Comment by gkatsev** [comment]
This probably isn't the right repo to ask this question as this repo is for the youtube tech for Video.js. Best to ask these questions on the main Video.js repo.

AVI won't play in browsers because just about every browser doesn't support that container format and we can only play the formats that browsers support.
In addition, it looks like the encoding of the video inside the container is HEVC based on the sample file names. Unfortunately, most browsers cannot play HEVC currently either. I think that Safari supports HEVC in some of the newer macOSes and probably on latest iOS on latest devices but I'm not positive on the specific support matrix there.

h264 is still, currently, your best bet to playing in the largest array of browsers.

Hope that helps.
