### ISSUE TITLE
Why this tech should be archived

### ISSUE THREAD

**Issue by techboyg5** [videojs/videojs-youtube#571]
As of September 25, 2018, YouTube made major changes to it's parameters:
* The showinfo parameter was removed. So all embedded YouTube players (including Video.js) now do not have control over the top bar of the video.
* The rel parameter doesn't completely hide related videos anymore. Now setting rel=0 only shows related videos from the same channel.

I think that the videojs-youtube tech should be archived, and encourage users to download videos locally and play them with Video.js.

Some reasons for this are:
* We need to keep the video player look clean. The addition of a top bar and related videos when finished clutters up the video. We just need the controls.
* Video.js is open-source software. **These YouTube requirements are adding closed-source features to open-source software, which is not okay.**

**Comment by txwizard** [comment]
Have you  actually tried to download a YouTube video? Though it can be done, it's messy and ugly. We all know that YT is a walled garden. I am thankful that they let us play in it at all, and I see no reason to abandon this tech just because you disagree with the vendor's politics. Man up and deal with it.

**Comment by gkatsev** [comment]
It would likely be good to write up the new limitations that YouTube imposes on us. However, I don't think it's a reason to archive this project. It still is nice to be able to have a youtube video next to an HLS stream or an mp4 in the same player, with mostly the same UI (since you can't turn off some of youtube's stuff anymore).

In addition, while there are ways of downloading YouTube videos, due to the various ways that videos are licensed on YouTube, we cannot encourage users to download them.
